### ISSUE TITLE
Compatibility with RabbitMQ 2.7

### ISSUE THREAD

**Issue by rafaelkaufmann** [jbrisbin/rabbitmq-webhooks#2]
Installing the plugin over RabbitMQ 2.7 on Mac OS Snow Leopard, broker loads with the following errors:

---

_WARNING_ Undefined function amqp_channel:register_default_consumer/2
_WARNING_ Undefined function ssl:seed/1

---

Thanks!

**Comment by jbrisbin** [comment]
Thanks for reporting this! I've updated the plugin to work with RabbitMQ 2.7. I updated the README too. 

I added two new items to the config file (username and virtual_host) and note that, in 2.7, you have to do "rabbitmq-plugins enable rabbit_webhooks" before you can use the plugin.

Let me know if there are any further issues.
